# Generated by Django 6.1 on 2026-08-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
        ('evaluations', '0001_initial'),
        ('parametrage', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='parametrage.periode'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='classe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametrage.classe'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametrage.matiere'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='periode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='parametrage.periode'),
        ),
        migrations.AddField(
            model_name='note',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='evaluations.evaluation'),
        ),
        migrations.AddField(
            model_name='note',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.inscription'),
        ),
        migrations.AddField(
            model_name='note',
            name='saisi_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to='personnel.personnel'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletin',
            unique_together={('inscription', 'periode', 'est_annuel')},
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('evaluation', 'inscription')},
        ),
    ]
