# Generated by Django 5.2.4 on 2026-08-12 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancienne_valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('nouvelle_valeur', models.DecimalField(decimal_places=2, max_digits=4)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_notes', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='evaluations.note')),
            ],
            options={
                'verbose_name': 'Modification de note',
                'verbose_name_plural': 'Modifications de notes',
                'ordering': ['-date_modification'],
            },
        ),
    ]
