# Generated by Django 5.2.17 on 2026-10-01 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_initial'),
        ('evaluations', '0003_notemodification'),
        ('parametrage', '0008_horairejournalier_affichage_cellule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceAPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex. C1.1, C2.3', max_length=20)),
                ('libelle', models.CharField(max_length=255)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_apc', to='parametrage.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_apc', to='parametrage.niveau')),
            ],
            options={
                'verbose_name': 'Compétence (APC)',
                'verbose_name_plural': 'Compétences (APC)',
                'ordering': ['niveau', 'matiere', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ConseilDeClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conseil', models.DateField()),
                ('synthese_generale', models.TextField(blank=True, help_text='Bilan global de la classe sur la période')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils_de_classe', to='parametrage.classe')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils_de_classe', to='parametrage.periode')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseils_presides', to=settings.AUTH_USER_MODEL)),
                ('secretaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conseils_secretaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conseil de classe',
                'verbose_name_plural': 'Conseils de classe',
                'unique_together': {('classe', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='InscriptionGarderie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(choices=[('MATIN', 'Garderie matinale (6h30 - 7h30)'), ('SOIR', 'Étude surveillée / Garderie du soir (17h - 18h30)'), ('COMPLETE', 'Garderie complète (Matin & Soir)')], max_length=15)),
                ('tarif_mensuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_garderie', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Inscription Garderie / Périscolaire',
                'verbose_name_plural': 'Inscriptions Garderie / Périscolaire',
            },
        ),
        migrations.CreateModel(
            name='DelegueClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_delegue', models.CharField(choices=[('TITULAIRE', 'Délégué(e) titulaire'), ('SUPPLEANT', 'Délégué(e) suppléant(e)')], default='TITULAIRE', max_length=15)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegues', to='parametrage.classe')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mandats_delegue', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Délégué de classe',
                'verbose_name_plural': 'Délégués de classe',
                'unique_together': {('classe', 'annee_scolaire', 'eleve')},
            },
        ),
        migrations.CreateModel(
            name='EvaluationCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_maitrise', models.CharField(choices=[('NA', 'Non Acquis'), ('ECA', "En Cours d'Acquisition"), ('A', 'Acquis'), ('E', 'Expert')], max_length=5)),
                ('observations', models.CharField(blank=True, max_length=255)),
                ('date_evaluation', models.DateField(auto_now_add=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='evaluations.competenceapc')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_competences', to='eleves.inscription')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.periode')),
            ],
            options={
                'verbose_name': 'Évaluation de compétence',
                'verbose_name_plural': 'Évaluations de compétences',
                'unique_together': {('inscription', 'competence', 'periode')},
            },
        ),
        migrations.CreateModel(
            name='MentionConseil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mention', models.CharField(choices=[('FELICITATIONS', 'Félicitations du conseil'), ('TABLEAU_HONNEUR', "Tableau d'honneur"), ('ENCOURAGEMENTS', 'Encouragements'), ('AVERT_TRAVAIL', 'Avertissement travail'), ('AVERT_CONDUITE', 'Avertissement conduite')], max_length=20)),
                ('avis', models.CharField(blank=True, max_length=255)),
                ('conseil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='evaluations.conseildeclasse')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions_conseil', to='eleves.inscription')),
            ],
            options={
                'verbose_name': 'Mention / Avis du conseil',
                'verbose_name_plural': 'Mentions / Avis du conseil',
                'unique_together': {('conseil', 'inscription')},
            },
        ),
    ]
