# Generated by Django 6.1 on 2026-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(editable=False, max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='eleves/photos/')),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('regime', models.CharField(choices=[('INTERNE', 'Interne'), ('EXTERNE', 'Externe'), ('DEMI', 'Demi-pensionnaire')], default='EXTERNE', max_length=10)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('TRANSFERE', 'Transféré'), ('RADIE', 'Radié'), ('DIPLOME', 'Diplômé')], default='ACTIF', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('statut_inscription', models.CharField(choices=[('NOUVEAU', 'Nouvel élève'), ('REDOUBLANT', 'Redoublant'), ('TRANSFERT', 'Transfert entrant'), ('ANCIEN', 'Ancien (réinscription)')], max_length=12)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='ACTIVE', max_length=10)),
                ('decision_fin_annee', models.CharField(blank=True, help_text="Ex. Admis(e), Redouble, Exclu(e) — renseigné en fin d'année", max_length=20)),
            ],
            options={
                'ordering': ['-annee_scolaire', 'classe'],
            },
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('lien_parente', models.CharField(choices=[('PERE', 'Père'), ('MERE', 'Mère'), ('TUTEUR', 'Tuteur légal'), ('AUTRE', 'Autre')], max_length=10)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('contact_urgence', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Tuteur / Parent',
            },
        ),
    ]
