# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
        ('parametrage', '0008_horairejournalier_affichage_cellule_and_more'),
        ('personnel', '0003_disponibiliteenseignant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creneau', models.CharField(blank=True, help_text='Ex. 08:00 - 09:00 ou Matin', max_length=50)),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent(e)'), ('ABSENT', 'Absent(e)'), ('RETARD', 'En retard'), ('INFIRMERIE', "À l'infirmerie")], default='PRESENT', max_length=15)),
                ('justifie', models.BooleanField(default=False)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels', to='personnel.affectation')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appels_enregistres', to=settings.AUTH_USER_MODEL)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appels', to='eleves.inscription')),
            ],
            options={
                'verbose_name': "Pointage d'assiduité / Appel",
                'verbose_name_plural': "Pointages d'assiduité / Appels",
                'ordering': ['-date', 'inscription__classe', 'inscription__eleve'],
                'unique_together': {('inscription', 'date', 'creneau')},
            },
        ),
        migrations.CreateModel(
            name='ConseilDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_conseil', models.DateField()),
                ('motif', models.TextField()),
                ('composition_membres', models.TextField(help_text='Liste des membres présents')),
                ('proces_verbal', models.TextField(blank=True)),
                ('decision', models.TextField()),
                ('convocation_envoyee', models.BooleanField(default=False)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.anneescolaire')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conseils_discipline', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Conseil de discipline',
                'verbose_name_plural': 'Conseils de discipline',
            },
        ),
        migrations.CreateModel(
            name='IncidentDisciplinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_incident', models.DateTimeField()),
                ('type_incident', models.CharField(max_length=150)),
                ('gravite', models.CharField(choices=[('FAIBLE', 'Faible (avertissement verbal)'), ('MOYENNE', 'Moyenne (perturbation, insolence)'), ('GRAVE', 'Grave (bagarre, triche, dégradation)'), ('TRES_GRAVE', 'Très grave (violence, vol, stupéfiants)')], default='MOYENNE', max_length=15)),
                ('description', models.TextField()),
                ('lieu', models.CharField(blank=True, max_length=100)),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents_disciplinaires', to='eleves.eleve')),
                ('signale_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_signales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident disciplinaire',
                'verbose_name_plural': 'Incidents disciplinaires',
                'ordering': ['-date_incident'],
            },
        ),
        migrations.CreateModel(
            name='JustificatifAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(blank=True, null=True, upload_to='viescolaire/justificatifs/')),
                ('motif', models.TextField()),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=15)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('appel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='viescolaire.appel')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificatifs_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Justificatif d'absence",
                'verbose_name_plural': "Justificatifs d'absence",
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('AVERT_TRAVAIL', 'Avertissement travail'), ('AVERT_CONDUITE', 'Avertissement conduite'), ('BLAME', 'Blâme'), ('RETENUE', 'Retenue / Heure de colle'), ('EXCL_TEMP', 'Exclusion temporaire'), ('EXCL_DEF', 'Exclusion définitive')], max_length=20)),
                ('motif', models.TextField()),
                ('date_decision', models.DateField(auto_now_add=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('decide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanctions_decidees', to=settings.AUTH_USER_MODEL)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='eleves.eleve')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='viescolaire.incidentdisciplinaire')),
            ],
            options={
                'verbose_name': 'Sanction disciplinaire',
                'verbose_name_plural': 'Sanctions disciplinaires',
            },
        ),
        migrations.CreateModel(
            name='Retenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('travail_a_faire', models.TextField(blank=True)),
                ('effectuee', models.BooleanField(default=False)),
                ('surveillant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retenues_surveillees', to=settings.AUTH_USER_MODEL)),
                ('sanction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retenue', to='viescolaire.sanction')),
            ],
            options={
                'verbose_name': 'Retenue / Colle',
                'verbose_name_plural': 'Retenues / Colles',
            },
        ),
    ]
