# Generated by Django 5.2.17 on 2026-10-01 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_initial'),
        ('personnel', '0003_disponibiliteenseignant'),
        ('viescolaire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['date', 'statut'], name='viescolaire_date_2b6339_idx'),
        ),
        migrations.AddIndex(
            model_name='appel',
            index=models.Index(fields=['inscription', 'date'], name='viescolaire_inscrip_2e83e6_idx'),
        ),
        migrations.AddIndex(
            model_name='incidentdisciplinaire',
            index=models.Index(fields=['eleve', 'date_incident'], name='viescolaire_eleve_i_99622b_idx'),
        ),
    ]
