# Generated by Django 6.1 on 2026-08-12 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='parametrage.anneescolaire')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='parametrage.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='parametrage.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='CreneauEmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=3)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('salle', models.CharField(blank=True, max_length=50)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='personnel.affectation')),
            ],
            options={
                'verbose_name': "Créneau d'emploi du temps",
                'verbose_name_plural': 'Emploi du temps',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('fonction', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('CENSEUR', 'Censeur / Direction des études'), ('SECRETAIRE', 'Secrétaire'), ('COMPTABLE', 'Comptable'), ('SURVEILLANT', 'Surveillant'), ('AUTRE', 'Autre')], max_length=15)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiche_personnel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personnel',
                'ordering': ['nom', 'prenoms'],
            },
        ),
        migrations.AddField(
            model_name='affectation',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='personnel.personnel'),
        ),
        migrations.AlterUniqueTogether(
            name='affectation',
            unique_together={('personnel', 'classe', 'matiere', 'annee_scolaire')},
        ),
    ]
