# Generated by Django 5.2.4 on 2026-08-12 14:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='tarif_horaire',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Montant payé par heure de cours pour cet enseignant sur cette classe/matière.', max_digits=10),
        ),
    ]
