# Generated by Django 5.2.4 on 2026-09-14 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0008_horairejournalier_affichage_cellule_and_more'),
        ('personnel', '0002_affectation_tarif_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUN', 'Lundi'), ('MAR', 'Mardi'), ('MER', 'Mercredi'), ('JEU', 'Jeudi'), ('VEN', 'Vendredi'), ('SAM', 'Samedi')], max_length=3)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_enseignants', to='parametrage.anneescolaire')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='personnel.personnel')),
            ],
            options={
                'verbose_name': 'Disponibilité Enseignant',
                'verbose_name_plural': 'Disponibilités Enseignants',
                'ordering': ['jour', 'heure_debut'],
            },
        ),
    ]
