# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0003_disponibiliteenseignant'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeanceCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('creneau', models.CharField(help_text='Ex. 08:00 - 10:00', max_length=50)),
                ('titre_chapitre', models.CharField(max_length=200)),
                ('contenu_dispense', models.TextField(help_text='Notions abordées, cours, exercices effectués en classe')),
                ('objectifs_vises', models.TextField(blank=True, help_text='Objectifs pédagogiques de la séance')),
                ('fichier_support', models.FileField(blank=True, null=True, upload_to='cahier_texte/supports/')),
                ('date_saisie', models.DateTimeField(auto_now_add=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seances_cahier_texte', to='personnel.affectation')),
            ],
            options={
                'verbose_name': 'Séance de cours',
                'verbose_name_plural': 'Séances de cours',
                'ordering': ['-date', 'creneau'],
            },
        ),
        migrations.CreateModel(
            name='DevoirMaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('date_prescription', models.DateField()),
                ('date_limite', models.DateField(help_text="Date d'échéance pour rendre le devoir")),
                ('consignes', models.TextField()),
                ('fichier_sujet', models.FileField(blank=True, null=True, upload_to='cahier_texte/devoirs/')),
                ('est_note', models.BooleanField(default=False)),
                ('bareme', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoirs_maison', to='personnel.affectation')),
                ('seance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devoirs', to='cahier_texte.seancecours')),
            ],
            options={
                'verbose_name': 'Devoir de maison',
                'verbose_name_plural': 'Devoirs de maison',
                'ordering': ['-date_limite'],
            },
        ),
    ]
