# Generated by Django 5.2.17 on 2026-10-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cahier_texte', '0001_initial'),
        ('personnel', '0003_disponibiliteenseignant'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='devoirmaison',
            index=models.Index(fields=['affectation', 'date_limite'], name='cahier_text_affecta_692178_idx'),
        ),
        migrations.AddIndex(
            model_name='seancecours',
            index=models.Index(fields=['affectation', 'date'], name='cahier_text_affecta_80de1e_idx'),
        ),
    ]
