# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage', '0008_horairejournalier_affichage_cellule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenoms', models.CharField(max_length=150)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=150)),
                ('etablissement_origine', models.CharField(blank=True, max_length=200)),
                ('classe_precedente', models.CharField(blank=True, max_length=50)),
                ('nom_parent', models.CharField(max_length=200)),
                ('telephone_parent', models.CharField(max_length=30)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('statut', models.CharField(choices=[('RECUE', 'Dossier reçu'), ('EN_EXAMEN', "En cours d'examen"), ('TEST_PROGRAMME', "Convoqué au test d'entrée"), ('ADMIS', 'Admis(e)'), ('REFUSE', 'Non retenu(e)'), ('INSCRIT', 'Inscription définitive validée')], default='RECUE', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('observations_direction', models.TextField(blank=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.anneescolaire')),
                ('niveau_souhaite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.niveau')),
            ],
            options={
                'verbose_name': "Demande d'admission",
                'verbose_name_plural': "Demandes d'admission",
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_piece', models.CharField(choices=[('ACTE', 'Acte de naissance'), ('BULLETIN', 'Dernier bulletin scolaire'), ('CERTIF', 'Certificat de scolarité / Radiation'), ('PHOTO', "Photo d'identité"), ('AUTRE', 'Autre pièce')], max_length=15)),
                ('fichier', models.FileField(upload_to='admissions/dossiers/')),
                ('verifie', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='admissions.demandeadmission')),
            ],
            options={
                'verbose_name': "Pièce justificative d'admission",
                'verbose_name_plural': "Pièces justificatives d'admission",
            },
        ),
        migrations.CreateModel(
            name='TestAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_test', models.DateField()),
                ('matiere', models.CharField(help_text='Ex. Français, Mathématiques', max_length=100)),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('note_sur', models.DecimalField(decimal_places=2, default=20.0, max_digits=4)),
                ('appreciation', models.CharField(blank=True, max_length=255)),
                ('admis', models.BooleanField(default=False)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='admissions.demandeadmission')),
            ],
            options={
                'verbose_name': "Test d'admission",
                'verbose_name_plural': "Tests d'admission",
            },
        ),
    ]
