# Generated by Django 5.2.17 on 2026-10-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('parametrage', '0008_horairejournalier_affichage_cellule_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='demandeadmission',
            index=models.Index(fields=['statut', 'date_soumission'], name='admissions__statut_00f3b5_idx'),
        ),
    ]
