# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuSemaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(help_text='Lundi de la semaine')),
                ('date_fin', models.DateField(help_text='Vendredi de la semaine')),
                ('lundi', models.TextField()),
                ('mardi', models.TextField()),
                ('mercredi', models.TextField()),
                ('jeudi', models.TextField()),
                ('vendredi', models.TextField()),
            ],
            options={
                'verbose_name': 'Menu de la semaine',
                'verbose_name_plural': 'Menus de la semaine',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='InscriptionCantine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(choices=[('ANNUEL', 'Abonnement annuel'), ('MENSUEL', 'Abonnement mensuel'), ('TICKET', 'Tickets repas au coup par coup')], default='MENSUEL', max_length=15)),
                ('tarif', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('allergies', models.CharField(blank=True, help_text='Ex. Arachides, gluten, lactose', max_length=255)),
                ('regime_special', models.CharField(blank=True, help_text='Ex. Sans porc, végétarien', max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_cantine', to='eleves.inscription')),
            ],
            options={
                'verbose_name': 'Inscription Cantine',
                'verbose_name_plural': 'Inscriptions Cantine',
            },
        ),
        migrations.CreateModel(
            name='PresenceRepas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=True)),
                ('heure_passage', models.TimeField(auto_now_add=True)),
                ('inscription_cantine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='cantine.inscriptioncantine')),
            ],
            options={
                'verbose_name': 'Présence au réfectoire',
                'verbose_name_plural': 'Présences au réfectoire',
                'unique_together': {('inscription_cantine', 'date')},
            },
        ),
    ]
