# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheMedicale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe_sanguin', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('INCONNU', 'Inconnu')], default='INCONNU', max_length=10)),
                ('allergies', models.TextField(blank=True, help_text='Allergies médicamenteuses ou alimentaires connues')),
                ('affections_chroniques', models.TextField(blank=True, help_text='Ex. Asthme, diabète, drépanocytose, épilepsie')),
                ('medecin_traitant', models.CharField(blank=True, max_length=150)),
                ('telephone_medecin', models.CharField(blank=True, max_length=30)),
                ('remarques_urgences', models.TextField(blank=True, help_text="Instructions spéciales en cas de crise ou d'accident")),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_medicale', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Fiche médicale',
                'verbose_name_plural': 'Fiches médicales',
            },
        ),
        migrations.CreateModel(
            name='PassageInfirmerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_entree', models.DateTimeField(auto_now_add=True)),
                ('date_heure_sortie', models.DateTimeField(blank=True, null=True)),
                ('motif', models.CharField(help_text='Ex. Céphalées, plaie légère, fièvre, malaise', max_length=200)),
                ('soins_administres', models.TextField(help_text='Pansement, prise de température, repos, paracétamol...')),
                ('issue', models.CharField(choices=[('RETOUR_CLASSE', 'Retour en classe'), ('REPOS', "Repos à l'infirmerie"), ('RETOUR_DOMICILE', 'Retour au domicile (parents prévenus)'), ('EVACUATION', 'Évacuation vers un centre hospitalier')], default='RETOUR_CLASSE', max_length=20)),
                ('parent_prevenu', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites_infirmerie', to='eleves.eleve')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soins_infirmerie_dispenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Passage à l'infirmerie",
                'verbose_name_plural': "Passages à l'infirmerie",
                'ordering': ['-date_heure_entree'],
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_vaccin', models.CharField(max_length=100)),
                ('date_administration', models.DateField()),
                ('rappel_prevu', models.DateField(blank=True, null=True)),
                ('centre_ou_medecin', models.CharField(blank=True, max_length=150)),
                ('fiche_medicale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='sante.fichemedicale')),
            ],
            options={
                'verbose_name': 'Vaccination',
                'verbose_name_plural': 'Vaccinations',
            },
        ),
    ]
