# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
        ('parametrage', '0008_horairejournalier_affichage_cellule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_barre', models.CharField(max_length=50, unique=True)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USE', 'Usagé'), ('DEGRADE', 'Dégradé / Abîmé')], default='BON', max_length=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Exemplaire physique',
                'verbose_name_plural': 'Exemplaires physiques',
            },
        ),
        migrations.CreateModel(
            name='Ouvrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=30)),
                ('categorie', models.CharField(choices=[('MANUEL', 'Manuel scolaire'), ('ROMAN', 'Roman / Littérature'), ('DICTIONNAIRE', 'Dictionnaire / Encyclopédie'), ('BD', 'Bande dessinée'), ('REVUE', 'Revue / Périodique'), ('AUTRE', 'Autre')], default='MANUEL', max_length=20)),
                ('editeur', models.CharField(blank=True, max_length=100)),
                ('annee_publication', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('emplacement', models.CharField(blank=True, help_text='Rayon, étagère', max_length=50)),
            ],
            options={
                'verbose_name': 'Ouvrage',
                'verbose_name_plural': 'Ouvrages',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField(auto_now_add=True)),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_effective', models.DateField(blank=True, null=True)),
                ('etat_retour', models.CharField(blank=True, choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USE', 'Usagé'), ('DEGRADE', 'Dégradé / Abîmé')], max_length=10)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts_bibliotheque', to='eleves.eleve')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.exemplaire')),
            ],
            options={
                'verbose_name': 'Emprunt de livre',
                'verbose_name_plural': 'Emprunts de livres',
                'ordering': ['-date_emprunt'],
            },
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='ouvrage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='bibliotheque.ouvrage'),
        ),
        migrations.CreateModel(
            name='PretManuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caution_versee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('etat_depart', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USE', 'Usagé'), ('DEGRADE', 'Dégradé / Abîmé')], default='BON', max_length=10)),
                ('etat_retour', models.CharField(blank=True, choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USE', 'Usagé'), ('DEGRADE', 'Dégradé / Abîmé')], max_length=10)),
                ('restitue', models.BooleanField(default=False)),
                ('date_pret', models.DateField(auto_now_add=True)),
                ('date_restitution', models.DateField(blank=True, null=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametrage.anneescolaire')),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_manuels', to='bibliotheque.exemplaire')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuels_pretes', to='eleves.inscription')),
            ],
            options={
                'verbose_name': 'Prêt de manuel scolaire',
                'verbose_name_plural': 'Prêts de manuels scolaires',
            },
        ),
    ]
