# Generated by Django 6.1 on 2026-08-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAdministratif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('ATTESTATION_REUSSITE', 'Attestation de réussite'), ('RELEVE_NOTES', 'Relevé de notes'), ('LISTE_CLASSE', 'Liste de classe'), ('CONVOCATION', 'Convocation'), ('AVIS_RELANCE', 'Avis de relance'), ('CARTE_SCOLAIRE', 'Carte scolaire')], max_length=25)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='documents_administratifs/')),
            ],
            options={
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='ModeleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('ATTESTATION_REUSSITE', 'Attestation de réussite'), ('RELEVE_NOTES', 'Relevé de notes'), ('LISTE_CLASSE', 'Liste de classe'), ('CONVOCATION', 'Convocation'), ('AVIS_RELANCE', 'Avis de relance'), ('CARTE_SCOLAIRE', 'Carte scolaire')], max_length=25, unique=True)),
                ('en_tete_html', models.TextField(blank=True)),
                ('pied_page_html', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='modeles/logos/')),
                ('mentions_legales', models.TextField(blank=True)),
            ],
        ),
    ]
