# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(choices=[('LIGHTY', 'Lighty SMS (Bénin)'), ('AFRICASTALKING', "Africa's Talking"), ('TWILIO', 'Twilio'), ('GENERIQUE', 'Passerelle HTTP Générique')], default='LIGHTY', max_length=20)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('sender_id', models.CharField(help_text="Nom d'expéditeur affiché (max 11 caractères)", max_length=11)),
                ('solde_sms', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuration SMS',
                'verbose_name_plural': 'Configurations SMS',
            },
        ),
        migrations.CreateModel(
            name='CampagneSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('cible', models.CharField(choices=[('TOUS', 'Tous les parents'), ('CLASSE', 'Par classe'), ('NIVEAU', 'Par niveau'), ('IMPAYES', 'Parents ayant des impayés')], max_length=15)),
                ('contenu', models.TextField(help_text='Texte du SMS (limité à 160 caractères recommandé)')),
                ('nb_destinataires', models.PositiveIntegerField(default=0)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('envoyee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campagne SMS',
                'verbose_name_plural': 'Campagnes SMS',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sujet', models.CharField(max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_dernier_message', models.DateTimeField(auto_now=True)),
                ('cloturee', models.BooleanField(default=False)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-date_dernier_message'],
            },
        ),
        migrations.CreateModel(
            name='MessageInterne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='communication/pieces/')),
                ('lu', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='communication.conversation')),
            ],
            options={
                'verbose_name': 'Message interne',
                'verbose_name_plural': 'Messages internes',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='MessageSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire_telephone', models.CharField(max_length=30)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ENVOYE', 'Envoyé avec succès'), ('ECHOUE', "Échec d'envoi")], default='EN_ATTENTE', max_length=15)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('reponse_passerelle', models.CharField(blank=True, max_length=255)),
                ('cout', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_envoyes', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Message SMS',
                'verbose_name_plural': 'Messages SMS',
                'ordering': ['-date_envoi'],
            },
        ),
    ]
