# Generated by Django 5.2.17 on 2026-10-01 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('eleves', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messageinterne',
            index=models.Index(fields=['conversation', 'date_envoi'], name='communicati_convers_63de7e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesms',
            index=models.Index(fields=['statut', 'date_envoi'], name='communicati_statut_22034b_idx'),
        ),
        migrations.AddIndex(
            model_name='messagesms',
            index=models.Index(fields=['destinataire_telephone'], name='communicati_destina_1d35eb_idx'),
        ),
    ]
