# Generated by Django 6.1 on 2026-08-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. 2026-2027', max_length=20, unique=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('est_courante', models.BooleanField(default=False)),
                ('cloturee', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Année scolaire',
                'verbose_name_plural': 'Années scolaires',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='GrilleTarifaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Grille tarifaire',
                'verbose_name_plural': 'Grilles tarifaires',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('coefficient', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
            ],
            options={
                'ordering': ['niveau', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. 6ème', max_length=50)),
                ('cycle', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], max_length=10)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['cycle', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. 1er trimestre', max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
            options={
                'ordering': ['annee_scolaire', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='TypeFrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. Inscription, Scolarité, Examen, Tenue', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BaremeEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_max', models.DecimalField(decimal_places=1, default=20, max_digits=4)),
                ('seuil_passage', models.DecimalField(decimal_places=1, default=10, max_digits=4)),
                ('seuil_mention_bien', models.DecimalField(decimal_places=1, default=14, max_digits=4)),
                ('seuil_mention_tres_bien', models.DecimalField(decimal_places=1, default=16, max_digits=4)),
                ('annee_scolaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bareme', to='parametrage.anneescolaire')),
            ],
            options={
                'verbose_name': "Barème d'évaluation",
                'verbose_name_plural': "Barèmes d'évaluation",
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. 6ème A', max_length=50)),
                ('effectif_max', models.PositiveSmallIntegerField(default=50)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='parametrage.anneescolaire')),
            ],
            options={
                'ordering': ['niveau__ordre', 'libelle'],
            },
        ),
    ]
