# Generated by Django 6.1 on 2026-08-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parametrage', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='enseignant_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='grilletarifaire',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_tarifaires', to='parametrage.anneescolaire'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignants',
            field=models.ManyToManyField(blank=True, related_name='matieres_enseignees', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='parametrage.niveau'),
        ),
        migrations.AddField(
            model_name='grilletarifaire',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grilles_tarifaires', to='parametrage.niveau'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='parametrage.niveau'),
        ),
        migrations.AddField(
            model_name='periode',
            name='annee_scolaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='parametrage.anneescolaire'),
        ),
        migrations.AddField(
            model_name='grilletarifaire',
            name='type_frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.typefrais'),
        ),
        migrations.AlterUniqueTogether(
            name='matiere',
            unique_together={('libelle', 'niveau')},
        ),
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together={('niveau', 'annee_scolaire', 'libelle')},
        ),
        migrations.AlterUniqueTogether(
            name='periode',
            unique_together={('annee_scolaire', 'ordre')},
        ),
        migrations.AlterUniqueTogether(
            name='grilletarifaire',
            unique_together={('niveau', 'annee_scolaire', 'type_frais')},
        ),
    ]
