# Generated by Django 5.2.4 on 2026-08-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraireJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. Journée continue (07:00–15:35)', max_length=100)),
                ('actif', models.BooleanField(default=False, help_text='Un seul horaire peut être actif à la fois.')),
                ('heure_debut_journee', models.TimeField(help_text='Heure de début des cours le matin.')),
                ('heure_fin_journee', models.TimeField(help_text='Heure de fin des cours le soir.')),
            ],
            options={
                'verbose_name': 'Horaire journalier',
                'verbose_name_plural': 'Horaires journaliers',
                'ordering': ['-actif', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PauseHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. Récréation, Pause déjeuner', max_length=100)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('horaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='parametrage.horairejournalier')),
            ],
            options={
                'ordering': ['horaire', 'heure_debut'],
            },
        ),
    ]
