# Generated by Django 5.2.4 on 2026-08-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0003_horairejournalier_pausehoraire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_officiel', models.CharField(default='GESTION SCOLAIRE', help_text="Nom figurant sur l'autorisation d'ouverture.", max_length=200)),
                ('sigle', models.CharField(blank=True, help_text='Ex. CEG, CS, CPG...', max_length=30)),
                ('devise', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='PNG fond transparent, idéalement ≥ 1000×1000 px.', null=True, upload_to='etablissement/')),
                ('adresse', models.CharField(blank=True, help_text='Rue / quartier', max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('commune', models.CharField(blank=True, max_length=100)),
                ('pays', models.CharField(default='Bénin', max_length=100)),
                ('boite_postale', models.CharField(blank=True, help_text='BP', max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.URLField(blank=True)),
                ('statut_juridique', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVE_LAIC', 'Privé laïc'), ('PRIVE_CONFESSIONNEL', 'Privé confessionnel')], default='PRIVE_LAIC', max_length=25)),
                ('categorie', models.CharField(choices=[('MATERNELLE', 'Maternelle'), ('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée'), ('COMPLEXE', 'Complexe scolaire')], default='COLLEGE', max_length=15)),
                ('ministere_tutelle', models.CharField(blank=True, default='', help_text='Ex. Ministère des Enseignements Secondaire, Technique et de la Formation Professionnelle', max_length=200)),
                ('numero_arrete', models.CharField(blank=True, help_text="Arrêté d'autorisation d'ouverture", max_length=100)),
                ('date_arrete', models.DateField(blank=True, null=True)),
                ('code_etablissement', models.CharField(blank=True, help_text="Matricule attribué par le ministère de l'Éducation", max_length=50)),
                ('annee_creation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fondateur', models.CharField(blank=True, max_length=150)),
                ('ifu', models.CharField(blank=True, help_text='Identifiant Fiscal Unique — obligatoire sur les factures au Bénin', max_length=30)),
                ('rccm', models.CharField(blank=True, help_text='Registre du Commerce et du Crédit Mobilier', max_length=50)),
                ('nom_directeur', models.CharField(blank=True, max_length=150)),
                ('nom_censeur', models.CharField(blank=True, max_length=150)),
                ('nom_comptable', models.CharField(blank=True, max_length=150)),
                ('mentions_legales', models.TextField(blank=True, help_text='Texte de pied de page (clause anti-falsification, validité...)')),
                ('regime_fiscal', models.CharField(blank=True, help_text='Ex. Exonération de TVA sur les frais de scolarité', max_length=200)),
                ('formule_certification', models.CharField(blank=True, default='', help_text='Formule de certification standard des certificats', max_length=255)),
            ],
            options={
                'verbose_name': 'Établissement',
                'verbose_name_plural': 'Établissement (configuration unique)',
            },
        ),
    ]
