# Generated by Django 5.2.4 on 2026-08-12 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0004_etablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogoEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, default='', help_text='Ex. Logo de la République, Logo du ministère, Logo du collège', max_length=100)),
                ('image', models.ImageField(help_text='PNG fond transparent, idéalement ≥ 1000×1000 px.', upload_to='etablissement/logos/')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text="Ordre d'affichage dans l'en-tête.")),
                ('en_tete', models.BooleanField(default=True, help_text="Coché = affiché dans l'en-tête de tous les documents générés.")),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='parametrage.etablissement')),
            ],
            options={
                'verbose_name': 'Logo',
                'verbose_name_plural': 'Logos',
                'ordering': ['ordre', 'pk'],
            },
        ),
    ]
