# Generated by Django 5.2.4 on 2026-08-12 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0005_logoetablissement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex. A1, C, D, F1', max_length=10, unique=True)),
                ('libelle', models.CharField(blank=True, help_text='Ex. Biologie-Géologie', max_length=120)),
            ],
            options={
                'verbose_name': 'Série',
                'verbose_name_plural': 'Séries',
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='matiere',
            name='coefficient',
        ),
        migrations.AlterField(
            model_name='niveau',
            name='libelle',
            field=models.CharField(help_text='Ex. 6ème, 2nde', max_length=50),
        ),
        migrations.AddField(
            model_name='niveau',
            name='serie',
            field=models.ForeignKey(blank=True, help_text='Série du second cycle (ex. D) — laisser vide en premier cycle.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveaux', to='parametrage.serie'),
        ),
        migrations.CreateModel(
            name='ClasseMatiereCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matiere_coefficients', to='parametrage.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients_par_classe', to='parametrage.matiere')),
            ],
            options={
                'verbose_name': 'Coefficient matière-classe',
                'verbose_name_plural': 'Coefficients matière-classe',
                'ordering': ['matiere__libelle'],
                'unique_together': {('classe', 'matiere')},
            },
        ),
    ]
