# Generated by Django 5.2.4 on 2026-08-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0006_serie_remove_matiere_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='tronc_commun',
            field=models.BooleanField(default=False, help_text="Matière du tronc commun : liée automatiquement à toutes les classes du niveau (à la création d'une classe comme d'une matière)."),
        ),
    ]
