# Generated by Django 5.2.4 on 2026-09-14 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametrage', '0007_matiere_tronc_commun'),
    ]

    operations = [
        migrations.AddField(
            model_name='horairejournalier',
            name='affichage_cellule',
            field=models.CharField(choices=[('MATIERE_PROF', 'Matière + Professeur'), ('MATIERE', 'Matière seule'), ('PROFESSEUR', 'Professeur seul')], default='MATIERE_PROF', help_text="Contenu affiché dans chaque case de l'emploi du temps.", max_length=15),
        ),
        migrations.AddField(
            model_name='horairejournalier',
            name='duree_creneau_base',
            field=models.PositiveSmallIntegerField(default=60, help_text="Durée d'un créneau de base en minutes (ex. 45, 55, 60)."),
        ),
        migrations.CreateModel(
            name='QuotaHoraireMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heures_par_semaine', models.DecimalField(decimal_places=1, help_text="Nombre d'heures de cours par semaine pour cette matière dans cette classe.", max_digits=4)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas_horaires', to='parametrage.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas_horaires', to='parametrage.matiere')),
            ],
            options={
                'verbose_name': 'Quota horaire',
                'verbose_name_plural': 'Quotas horaires',
                'ordering': ['matiere__libelle'],
                'unique_together': {('matiere', 'classe')},
            },
        ),
    ]
