# Generated by Django 5.2.4 on 2026-08-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='bloque_jusqua',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tentatives_connexion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
