# Generated by Django 5.2.17 on 2026-10-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_utilisateur_bloque_jusqua_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur / Direction'), ('CENSEUR', 'Censeur / Direction des études'), ('SECRETARIAT', 'Secrétariat'), ('COMPTABLE', 'Comptable / Caissier(ère)'), ('ENSEIGNANT', 'Enseignant'), ('PARENT', 'Parent / Élève'), ('SURVEILLANT', 'Surveillant général / Vie scolaire'), ('INFIRMIER', 'Infirmerie / Santé scolaire'), ('RESPONSABLE_CANTINE', 'Responsable cantine / Intendance'), ('SUPERADMIN', 'Super-administrateur technique')], default='SECRETARIAT', max_length=25),
        ),
    ]
