# Generated by Django 6.1 on 2026-08-12 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('SOLDEE', 'Soldée'), ('ANNULEE', 'Annulée (avoir)')], default='EMISE', max_length=10)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='factures/')),
            ],
            options={
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='ImputationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_impute', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money')], max_length=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('VALIDE', 'Validé'), ('ANNULE', 'Annulé'), ('REMBOURSE', 'Remboursé')], default='VALIDE', max_length=10)),
                ('motif_annulation', models.TextField(blank=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='Recu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='recus/')),
            ],
        ),
        migrations.CreateModel(
            name='Remise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_remise', models.CharField(choices=[('BOURSE', 'Bourse'), ('EXONERATION', 'Exonération partielle'), ('REDUCTION', 'Réduction commerciale')], max_length=15)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_echeance', models.DateField()),
                ('statut', models.CharField(choices=[('IMPAYE', 'Impayé'), ('PARTIEL', 'Partiellement payé'), ('PAYE', 'Payé')], default='IMPAYE', max_length=10)),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echeances', to='eleves.inscription')),
            ],
            options={
                'ordering': ['date_echeance'],
            },
        ),
    ]
