# Generated by Django 6.1 on 2026-08-12 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
        ('finances', '0001_initial'),
        ('parametrage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='echeance',
            name='type_frais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parametrage.typefrais'),
        ),
        migrations.AddField(
            model_name='facture',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='eleves.inscription'),
        ),
        migrations.AddField(
            model_name='imputationpaiement',
            name='echeance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='finances.echeance'),
        ),
        migrations.AddField(
            model_name='lignefacture',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='finances.facture'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='encaisse_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_encaisses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paiement',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='eleves.inscription'),
        ),
        migrations.AddField(
            model_name='imputationpaiement',
            name='paiement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imputations', to='finances.paiement'),
        ),
        migrations.AddField(
            model_name='recu',
            name='paiement',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recu', to='finances.paiement'),
        ),
        migrations.AddField(
            model_name='remise',
            name='accorde_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_accordees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='remise',
            name='inscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remises', to='eleves.inscription'),
        ),
    ]
