# Generated by Django 5.2.4 on 2026-08-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_initial'),
        ('personnel', '0002_affectation_tarif_horaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheDePaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('mois', models.PositiveSmallIntegerField(help_text='1 à 12')),
                ('annee', models.PositiveSmallIntegerField()),
                ('heures_total', models.DecimalField(decimal_places=2, help_text='Heures du mois (heures hebdo × 4,33)', max_digits=8)),
                ('montant_brut', models.DecimalField(decimal_places=2, help_text='Heures × tarifs horaires des affectations', max_digits=12)),
                ('statut', models.CharField(choices=[('CALCULEE', 'Calculée'), ('PAYEE', 'Payée'), ('ANNULEE', 'Annulée')], default='CALCULEE', max_length=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money')], default='ESPECES', max_length=15)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='fiches_paie/')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_de_paie', to='personnel.personnel')),
            ],
            options={
                'verbose_name': 'Fiche de paie',
                'verbose_name_plural': 'Fiches de paie',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('personnel', 'mois', 'annee')},
            },
        ),
    ]
