# Generated by Django 5.2.17 on 2026-10-01 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_fichedepaie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieDepense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('nature', models.CharField(choices=[('FONCTIONNEMENT', 'Fonctionnement courant (eau, élec, fournitures)'), ('INVESTISSEMENT', 'Investissement & Équipements'), ('MAINTENANCE', 'Entretien & Maintenance'), ('PEDAGOGIE', 'Activités pédagogiques & sorties'), ('AUTRE', 'Autre dépense')], default='FONCTIONNEMENT', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
            },
        ),
        migrations.CreateModel(
            name='ClotureCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('solde_ouverture', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_encaissements', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_decaissements', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('solde_theorique', models.DecimalField(decimal_places=2, help_text='Ouverture + Encaissements - Décaissements', max_digits=12)),
                ('solde_physique', models.DecimalField(decimal_places=2, help_text='Montant réel compté dans le coffre/tiroir', max_digits=12)),
                ('ecart', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('justification_ecart', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('cloture_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clotures_caisse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clôture de caisse journalière',
                'verbose_name_plural': 'Clôtures de caisse journalières',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_depense', models.DateField()),
                ('beneficiaire', models.CharField(help_text='Fournisseur ou prestataire payé', max_length=150)),
                ('justificatif_facture', models.FileField(blank=True, null=True, upload_to='finances/justificatifs_depenses/')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile Money')], default='ESPECES', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='finances.categoriedepense')),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense / Décaissement',
                'verbose_name_plural': 'Dépenses / Décaissements',
                'ordering': ['-date_depense', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='TransactionMobileMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money'), ('KKIAPAY', 'Kkiapay (Agrégateur)'), ('FEDAPAY', 'FedaPay (Agrégateur)'), ('AUTRE', 'Autre opérateur')], default='MTN', max_length=15)),
                ('reference_externe', models.CharField(help_text="ID transaction de l'opérateur", max_length=150, unique=True)),
                ('numero_client', models.CharField(max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('SUCCES', 'Paiement confirmé'), ('ECHOUE', 'Échoué / Annulé')], default='EN_ATTENTE', max_length=15)),
                ('signature_hmac', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('donnees_webhook', models.JSONField(blank=True, default=dict)),
                ('paiement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_momo', to='finances.paiement')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
                'ordering': ['-date_creation'],
            },
        ),
    ]
