# Generated by Django 5.2.17 on 2026-10-01 10:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleves', '0002_initial'),
        ('finances', '0004_categoriedepense_cloturecaisse_depense_and_more'),
        ('parametrage', '0008_horairejournalier_affichage_cellule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='echeance',
            index=models.Index(fields=['inscription', 'statut'], name='finances_ec_inscrip_1a5400_idx'),
        ),
        migrations.AddIndex(
            model_name='echeance',
            index=models.Index(fields=['date_echeance', 'statut'], name='finances_ec_date_ec_c02a03_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['inscription', 'date_paiement'], name='finances_pa_inscrip_0dc4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['mode_paiement', 'statut'], name='finances_pa_mode_pa_bd7d9c_idx'),
        ),
    ]
