# Generated by Django 5.2.17 on 2026-10-01 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArretTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_arret', models.CharField(max_length=150)),
                ('heure_passage_matin', models.TimeField()),
                ('heure_passage_soir', models.TimeField(blank=True, null=True)),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Arrêt de bus',
                'verbose_name_plural': 'Arrêts de bus',
                'ordering': ['ligne', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='LigneTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex. Ligne Nord - Akpakpa / Cotonou', max_length=150)),
                ('chauffeur', models.CharField(max_length=150)),
                ('telephone_chauffeur', models.CharField(max_length=30)),
                ('immatriculation_vehicule', models.CharField(max_length=50)),
                ('capacite_places', models.PositiveSmallIntegerField(default=30)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ligne de transport',
                'verbose_name_plural': 'Lignes de transport',
            },
        ),
        migrations.CreateModel(
            name='InscriptionTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(choices=[('ALLER_RETOUR', 'Aller et Retour'), ('ALLER_SIMPLE', 'Aller simple uniquement')], default='ALLER_RETOUR', max_length=15)),
                ('tarif_mensuel', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('arret', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.arrettransport')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_transport', to='eleves.inscription')),
                ('ligne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='transport.lignetransport')),
            ],
            options={
                'verbose_name': 'Abonnement transport',
                'verbose_name_plural': 'Abonnements transport',
            },
        ),
        migrations.AddField(
            model_name='arrettransport',
            name='ligne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='transport.lignetransport'),
        ),
    ]
